{
    "results": [
        {
            "bioguide_id": "H001064",
            "birthday": "1952-07-29",
            "chamber": "house",
            "contact_form": "http://dennyheck.house.gov/contact/email-me",
            "crp_id": "N00031557",
            "district": 10,
            "facebook_id": "547907568553615",
            "fax": "202-225-0129",
            "fec_ids": [
                "H0WA03161"
            ],
            "first_name": "Denny",
            "gender": "M",
            "govtrack_id": "412584",
            "icpsr_id": 21369,
            "in_office": true,
            "last_name": "Heck",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "425 Cannon House Office Building",
            "party": "D",
            "phone": "202-225-9740",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "02170",
            "title": "Rep",
            "twitter_id": "RepDennyHeck",
            "votesmart_id": 126058,
            "website": "http://dennyheck.house.gov",
            "youtube_id": "RepDennyHeck"
        },
        {
            "bioguide_id": "K000381",
            "birthday": "1974-01-01",
            "chamber": "house",
            "contact_form": "http://kilmer.house.gov/contact/email-me",
            "crp_id": "N00034453",
            "district": 6,
            "facebook_id": "450819048314124",
            "fax": null,
            "fec_ids": [
                "H2WA06129"
            ],
            "first_name": "Derek",
            "gender": "M",
            "govtrack_id": "412583",
            "icpsr_id": 21368,
            "in_office": true,
            "last_name": "Kilmer",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "1429 Longworth House Office Building",
            "party": "D",
            "phone": "202-225-5916",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "02169",
            "title": "Rep",
            "twitter_id": "RepDerekKilmer",
            "votesmart_id": 51516,
            "website": "http://kilmer.house.gov"
        },
        {
            "bioguide_id": "D000617",
            "birthday": "1962-02-17",
            "chamber": "house",
            "contact_form": "http://delbene.house.gov/contact-me/email-me",
            "crp_id": "N00030693",
            "district": 1,
            "facebook_id": "483962224987343",
            "fax": "202-226-1606",
            "fec_ids": [
                "H0WA08046"
            ],
            "first_name": "Suzan",
            "gender": "F",
            "govtrack_id": "412505",
            "icpsr_id": 31101,
            "in_office": true,
            "last_name": "DelBene",
            "middle_name": "K.",
            "name_suffix": null,
            "nickname": null,
            "office": "318 Cannon House Office Building",
            "party": "D",
            "phone": "202-225-6311",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "02096",
            "title": "Rep",
            "twitter_id": "RepDelBene",
            "votesmart_id": 126272,
            "website": "http://delbene.house.gov",
            "youtube_id": null
        },
        {
            "bioguide_id": "S000510",
            "birthday": "1965-06-15",
            "chamber": "house",
            "contact_form": "http://adamsmith.house.gov/Contact/",
            "crp_id": "N00007833",
            "district": 9,
            "facebook_id": "288586617834523",
            "fax": "202-225-5893",
            "fec_ids": [
                "H6WA09025"
            ],
            "first_name": "Adam",
            "gender": "M",
            "govtrack_id": "400379",
            "icpsr_id": 29768,
            "in_office": true,
            "last_name": "Smith",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "2264 Rayburn House Office Building",
            "party": "D",
            "phone": "202-225-8901",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "01528",
            "title": "Rep",
            "twitter_id": "RepAdamSmith",
            "votesmart_id": 845,
            "website": "http://www.house.gov/adamsmith",
            "youtube_id": "CongressmanAdamSmith"
        },
        {
            "bioguide_id": "R000578",
            "birthday": "1950-08-29",
            "chamber": "house",
            "contact_form": "http://reichert.house.gov/contact-me",
            "crp_id": "N00026885",
            "district": 8,
            "facebook_id": "91504302598",
            "fax": "202-225-4282",
            "fec_ids": [
                "H4WA08071"
            ],
            "first_name": "David",
            "gender": "M",
            "govtrack_id": "400660",
            "icpsr_id": 20536,
            "in_office": true,
            "last_name": "Reichert",
            "middle_name": "G.",
            "name_suffix": null,
            "nickname": null,
            "office": "1127 Longworth House Office Building",
            "party": "R",
            "phone": "202-225-7761",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "01810",
            "title": "Rep",
            "twitter_id": "davereichert",
            "votesmart_id": 51346,
            "website": "http://reichert.house.gov",
            "youtube_id": "repdavereichert"
        },
        {
            "bioguide_id": "M001111",
            "birthday": "1950-10-11",
            "chamber": "senate",
            "contact_form": "http://www.murray.senate.gov/public/index.cfm/contactme",
            "crp_id": "N00007876",
            "district": null,
            "facebook_id": null,
            "fax": "202-224-0238",
            "fec_ids": [
                "S2WA00189"
            ],
            "first_name": "Patty",
            "gender": "F",
            "govtrack_id": "300076",
            "icpsr_id": 49308,
            "in_office": true,
            "last_name": "Murray",
            "lis_id": "S229",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "154 Russell Senate Office Building",
            "party": "D",
            "phone": "202-224-2621",
            "senate_class": 3,
            "state": "WA",
            "state_name": "Washington",
            "state_rank": "senior",
            "term_end": "2017-01-03",
            "term_start": "2011-01-05",
            "thomas_id": "01409",
            "title": "Sen",
            "twitter_id": "pattymurray",
            "votesmart_id": 53358,
            "website": "http://www.murray.senate.gov",
            "youtube_id": "SenatorPattyMurray"
        },
        {
            "bioguide_id": "M001159",
            "birthday": "1969-05-22",
            "chamber": "house",
            "contact_form": "http://mcmorris.house.gov/contact-cathy1/",
            "crp_id": "N00026314",
            "district": 5,
            "facebook_id": "321618789771",
            "fax": "202-225-3392",
            "fec_ids": [
                "H4WA05077"
            ],
            "first_name": "Cathy",
            "gender": "F",
            "govtrack_id": "400659",
            "icpsr_id": 20535,
            "in_office": true,
            "last_name": "McMorris Rodgers",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "203 Cannon House Office Building",
            "party": "R",
            "phone": "202-225-2006",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "01809",
            "title": "Rep",
            "twitter_id": "cathymcmorris",
            "votesmart_id": 3217,
            "website": "http://mcmorris.house.gov",
            "youtube_id": "mcmorrisrodgers"
        },
        {
            "bioguide_id": "M000404",
            "birthday": "1936-12-28",
            "chamber": "house",
            "contact_form": "http://mcdermott.house.gov/index.php?option=com_content&amp;view=article&amp;id=476&amp;Itemid=8",
            "crp_id": "N00009829",
            "district": 7,
            "facebook_id": "246418928093",
            "fax": "202-225-6197",
            "fec_ids": [
                "H8WA07132"
            ],
            "first_name": "Jim",
            "gender": "M",
            "govtrack_id": "400262",
            "icpsr_id": 15613,
            "in_office": true,
            "last_name": "McDermott",
            "middle_name": "A.",
            "name_suffix": null,
            "nickname": null,
            "office": "1035 Longworth House Office Building",
            "party": "D",
            "phone": "202-225-3106",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "00766",
            "title": "Rep",
            "twitter_id": "RepJimMcDermott",
            "votesmart_id": 27128,
            "website": "http://mcdermott.house.gov",
            "youtube_id": "RepJimMcDermott"
        },
        {
            "bioguide_id": "L000560",
            "birthday": "1965-06-15",
            "chamber": "house",
            "contact_form": "http://larsen.house.gov/contact-rick",
            "crp_id": "N00009759",
            "district": 2,
            "facebook_id": "135654683137079",
            "fax": "202-225-4420",
            "fec_ids": [
                "H0WA02080"
            ],
            "first_name": "Rick",
            "gender": "M",
            "govtrack_id": "400232",
            "icpsr_id": 20145,
            "in_office": true,
            "last_name": "Larsen",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "2113 Rayburn House Office Building",
            "party": "D",
            "phone": "202-225-2605",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "01675",
            "title": "Rep",
            "twitter_id": "RepRickLarsen",
            "votesmart_id": 56231,
            "website": "http://larsen.house.gov",
            "youtube_id": "congressmanlarsen"
        },
        {
            "bioguide_id": "H001056",
            "birthday": "1978-11-03",
            "chamber": "house",
            "contact_form": "http://herrerabeutler.house.gov/contact/",
            "crp_id": "N00031559",
            "district": 3,
            "facebook_id": "177551525610164",
            "fax": "202-225-3478",
            "fec_ids": [
                "H0WA03187"
            ],
            "first_name": "Jaime",
            "gender": "F",
            "govtrack_id": "412486",
            "icpsr_id": 21187,
            "in_office": true,
            "last_name": "Herrera Beutler",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "1130 Longworth House Office Building",
            "party": "R",
            "phone": "202-225-3536",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "02071",
            "title": "Rep",
            "twitter_id": "herrerabeutler",
            "votesmart_id": 101907,
            "website": "http://herrerabeutler.house.gov",
            "youtube_id": "RepHerreraBeutler"
        },
        {
            "bioguide_id": "H000329",
            "birthday": "1941-02-07",
            "chamber": "house",
            "contact_form": "http://hastings.house.gov/news/email/",
            "crp_id": "N00009157",
            "district": 4,
            "facebook_id": "7507129675",
            "fax": "202-225-3251",
            "fec_ids": [
                "H2WA04041"
            ],
            "first_name": "Doc",
            "gender": "M",
            "govtrack_id": "400171",
            "icpsr_id": 29580,
            "in_office": true,
            "last_name": "Hastings",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "1203 Longworth House Office Building",
            "party": "R",
            "phone": "202-225-5816",
            "state": "WA",
            "state_name": "Washington",
            "term_end": "2015-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "00512",
            "title": "Rep",
            "twitter_id": "DocHastings",
            "votesmart_id": 22318,
            "website": "http://hastings.house.gov",
            "youtube_id": "RepDocHastings"
        },
        {
            "bioguide_id": "C000127",
            "birthday": "1958-10-13",
            "chamber": "senate",
            "contact_form": "http://www.cantwell.senate.gov/public/index.cfm/email-maria",
            "crp_id": "N00007836",
            "district": null,
            "facebook_id": null,
            "fax": "202-228-0514",
            "fec_ids": [
                "S8WA00194",
                "H2WA01054"
            ],
            "first_name": "Maria",
            "gender": "F",
            "govtrack_id": "300018",
            "icpsr_id": 39310,
            "in_office": true,
            "last_name": "Cantwell",
            "lis_id": "S275",
            "middle_name": null,
            "name_suffix": null,
            "nickname": null,
            "office": "311 Hart Senate Office Building",
            "party": "D",
            "phone": "202-224-3441",
            "senate_class": 1,
            "state": "WA",
            "state_name": "Washington",
            "state_rank": "junior",
            "term_end": "2019-01-03",
            "term_start": "2013-01-03",
            "thomas_id": "00172",
            "title": "Sen",
            "twitter_id": "CantwellPress",
            "votesmart_id": 27122,
            "website": "http://www.cantwell.senate.gov",
            "youtube_id": "SenatorCantwell"
        }
    ],
    "count": 12,
    "page": {
        "count": 12,
        "per_page": 20,
        "page": 1
    }
}